const mongoose = require('mongoose');

// A single multiple-choice question. correctIndex/explanation are only ever
// sent to the client AFTER submission (see testRoutes.js) so taking the
// quiz can't be trivially cheated via devtools.
const questionSchema = new mongoose.Schema(
  {
    questionText: { type: String, required: true },
    options: {
      type: [String],
      required: true,
      validate: (arr) => Array.isArray(arr) && arr.length === 4,
    },
    correctIndex: { type: Number, required: true, min: 0, max: 3 },
    explanation: { type: String, default: '' },
  },
  { _id: false }
);

const testSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    subject: { type: String, required: true, trim: true },
    topic: { type: String, default: '', trim: true },
    difficulty: { type: String, enum: ['easy', 'medium', 'hard'], default: 'medium' },
    // 'ai' = generated by the LLM for this exact subject/topic/difficulty.
    // 'fallback' = a small built-in generic practice bank, used only when
    // no OPENAI_API_KEY is configured or generation failed - never passed
    // off to the student as personalized AI content.
    source: { type: String, enum: ['ai', 'fallback'], default: 'fallback' },
    questions: [questionSchema],
  },
  { timestamps: true }
);

module.exports = mongoose.model('Test', testSchema);
